services:
  _defaults:
    public: true

  prestashop.module.ciklik.module:
    class: Ciklik
    factory: ['Module', 'getInstanceByName']
    arguments:
      - "ciklik"

  prestashop.module.ciklik.context:
    class: Context
    factory: ['Context', 'getContext']

  #####################
  # PrestaShop Account
  prestashop.module.ciklik.ps_accounts_installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    arguments:
      - '5.0'

  prestashop.module.ciklik.ps_accounts_facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    arguments:
      - '@prestashop.module.ciklik.ps_accounts_installer'

  #####################
  # PrestaShop Billing

  prestashop.module.ciklik.ps_billings_context_wrapper:
    class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    arguments:
      - '@prestashop.module.ciklik.ps_accounts_facade'
      - '@prestashop.module.ciklik.context'
      - true # if true, enables the sandbox mode, if false or empty, disables it

  prestashop.module.ciklik.ps_billings_facade:
    class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
    public: true
    arguments:
      - '@prestashop.module.ciklik.ps_billings_context_wrapper'
      - '@prestashop.module.ciklik.module'

  # Remove this if you do not need BillingService
  prestashop.module.ciklik.ps_billings_service:
    class: 'PrestaShopCorp\Billing\Services\BillingService'
    public: true
    arguments:
      - '@prestashop.module.ciklik.ps_billings_context_wrapper'
      - '@prestashop.module.ciklik.module'
